import type { Event } from "./types"

// Mock data for development (will be replaced with real database queries)
export const mockEvents: Event[] = [
  {
    id: "1",
    title: "Rock in Rio 2025",
    description:
      "O maior festival de música do mundo está de volta! Prepare-se para uma experiência inesquecível com os maiores artistas nacionais e internacionais.",
    date: "2025-09-15T18:00:00Z",
    location: "Cidade do Rock - Rio de Janeiro, RJ",
    image_url: "/rock-concert-festival-stage-lights-crowd.jpg",
    price: 450.0,
    total_tickets: 100000,
    available_tickets: 100000,
    category: "show",
    status: "active",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "2",
    title: "Jantar Harmonizado com Chef Erick Jacquin",
    description:
      "Uma noite exclusiva com menu degustação de 7 pratos harmonizados com vinhos selecionados. Experiência gastronômica única comandada pelo renomado Chef Erick Jacquin.",
    date: "2025-06-20T20:00:00Z",
    location: "Restaurante Président - São Paulo, SP",
    image_url: "/elegant-fine-dining-restaurant-table-wine.jpg",
    price: 850.0,
    total_tickets: 50,
    available_tickets: 50,
    category: "jantar",
    status: "active",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "3",
    title: "TEDx São Paulo 2025",
    description:
      "Ideias que valem a pena espalhar. Palestrantes inspiradores compartilhando suas experiências e visões sobre tecnologia, inovação, sustentabilidade e futuro.",
    date: "2025-07-10T09:00:00Z",
    location: "Teatro Bradesco - São Paulo, SP",
    image_url: "/ted-talk-conference-stage-speaker-audience.jpg",
    price: 120.0,
    total_tickets: 500,
    available_tickets: 500,
    category: "palestra",
    status: "active",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "4",
    title: "Sertanejo Universitário - Henrique & Juliano",
    description:
      "A dupla mais querida do Brasil em um show imperdível! Sucessos que marcaram gerações e as novidades do novo álbum.",
    date: "2025-08-05T21:00:00Z",
    location: "Allianz Parque - São Paulo, SP",
    image_url: "/country-music-concert-stage-performance.jpg",
    price: 180.0,
    total_tickets: 45000,
    available_tickets: 45000,
    category: "show",
    status: "active",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "5",
    title: "Jantar Italiano Tradicional",
    description:
      "Noite especial celebrando a culinária italiana com receitas tradicionais da Nonna. Massa fresca, molhos artesanais e sobremesas irresistíveis.",
    date: "2025-06-30T19:30:00Z",
    location: "Trattoria Bella Vista - Belo Horizonte, MG",
    image_url: "/italian-restaurant-pasta-dinner-candles.jpg",
    price: 280.0,
    total_tickets: 40,
    available_tickets: 40,
    category: "jantar",
    status: "active",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "6",
    title: "Palestra: O Futuro da Inteligência Artificial",
    description:
      "Especialistas em IA discutem os avanços recentes, aplicações práticas e os desafios éticos da inteligência artificial no mundo moderno.",
    date: "2025-07-25T14:00:00Z",
    location: "Centro de Convenções Frei Caneca - São Paulo, SP",
    image_url: "/technology-conference-ai-presentation.jpg",
    price: 80.0,
    total_tickets: 300,
    available_tickets: 300,
    category: "palestra",
    status: "active",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]
